Repository liquality/atomicagent, pull requests merged in 2021-12, with the labels that each got.

#399 feat: Update solana packages to 1.11.0
  package-lock.json
  package.json
Labels: 🔍 Ready for Review

#398 feat: Update terra packages to 1.11.0
  package-lock.json
  package.json
Labels: ✅ Approved

#397 feat: Update near packages to 1.11.0
  package-lock.json
  package.json
Labels: 🔍 Ready for Review

#400 feat: Update all of the cal packages to 1.11.0
  package-lock.json
  package.json
Labels: 🔍 Ready for Review, ✅ Approved

#401 feat: added renovate.json
  .github/CODEOWNERS
  renovate.json
Labels: 🔍 Ready for Review

#403 Updated assets and markets for migrate seeding
  src/migrate/data/assets.json
  src/migrate/data/markets.json
Labels: 🔍 Ready for Review, size/XL

#404 feat: override rpc url from config.toml for solana and terra
  src/utils/clients.js
Labels: 🔍 Ready for Review, ✅ Approved, size/XS
