Repository liquality/atomicagent, pull requests merged in 2022-06, with the labels that each got.

#442 feat(near_helper): added near_helper to the client
  sample.config.toml
  src/utils/clients.js
Labels: ✅ Approved, size/S

#443 fix(url): near helper url
  src/utils/clients.js
Labels: 🔍 Ready for Review, size/XS

#445 Update ensureUserAgentCompatible.js
  src/middlewares/ensureUserAgentCompatible.js
Labels: ✅ Approved, size/XS

#444 Removed caret and tilde
  README.md
  package.json
  yarn.lock
Labels: ✅ Approved, size/XXL
